apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dns-config
  namespace: {{ .Release.Namespace }}
data:
  LISTEN_ADDR: {{ .Values.config.listenAddr | quote }}
  UPSTREAM_DNS: {{ .Values.config.upstreamDns | quote }}
  DEFAULT_ZONE: {{ .Values.config.defaultZone | quote }}
  ZONE_MAP: {{ .Values.config.zoneMap | quote }}
  MANAGED_DOMAINS: {{ .Values.config.managedDomains | quote }}
  GEOIP_PATH: {{ .Values.config.geoipPath | quote }}
