apiVersion: v2
name: rest-api-java
description: REST API Java (Spring Boot) — origen para la Zonal Cache del Proyecto 2 IC-7602
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - spring-boot
  - java
  - rest-api
maintainers:
  - name: Equipo P2 IC-7602
