apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-firebase-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  firebase-service-account.json: {{ .Values.firebaseServiceAccount | default "{}" | quote }}
