apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    app: zonal-cache
    release: {{ .Release.Name }}
spec:
  selector:
    app: zonal-cache
    release: {{ .Release.Name }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
